name: deploy terraform code  to create az resources

on:
    push:
        branches:
            - main

jobs:
    build:
     runs-on: ubuntu-latest

     steps:

       - name: checkout code
         uses: actions/checkout@v5.0.0

       - name: Azure Login
         uses: Azure/login@v2.3.0
         with:
            creds: ${{secrets.AZURE_CREDENTIALS}}

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2.0.3

       - name: Initialise terraform
         run: terraform init

       - name: validate your code
         run: terraform validate

       - name: Plan terraform
         run:  terraform plan

       - name: deploy terraform
         uses: terraform apply --auto-approve
         