name: Deploy terraform code

on:
    push:
        branches:
           - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v5.0.0

            - name: Az login
              uses: Azure/login@v2.3.0
              with:
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: install terraform
              uses: hashicorp/setup-terraform@v2.0.3

            - name: terraform init
              run: terraform init

            - name: terraform validate code
              run: terraform validate

            - name: terraform format
              run: terraform fmt

            - name: terraform plan
              run: terraform plan

            - name: terraform apply
              run: terraform apply --auto-approve
                

